### ISSUE TITLE
关于agent坐标和车道环境的一些疑问

### ISSUE THREAD

**Issue by wwwwssssa** [ZikangZhou/QCNet#10]
Hello，Dr Zhou，请问，1. 若想在现实中实现这个模型或HiVT模型，必须像argoverse数据集那样给出所有agent在空间中的绝对坐标吗？
2. 现有的车辆轨迹预测方法大多数都是在公开数据集中进行的，若想实现这些方法，是否也需要提前将环境信息（车道线，交通灯，人行道等）构建好？
期待您的解答，谢谢！！！

**Comment by ZikangZhou** [comment]
agent坐标是需要的，但是高精地图不一定需要。没有高精地图的话需要把模型里跟地图相关的模块全部去掉再训练模型。

**Comment by wwwwssssa** [comment]
**感谢您的回答**，之前自己也试过，参考argoverseV1数据集，只构建车道线的信息和智能体的轨迹，用HiVT模型，是可以实现预测的。
而感知和路径规划用到的坐标系都是以车为原点的frenet坐标系，得到的智能体坐标都是与自车的相对位置，那是不是必须将这些**相对位置坐标转换成在同一原点坐标系下的坐标**？
**再次感谢！**

**Comment by ZikangZhou** [comment]
只要保证所有的坐标都处在同一个坐标系中就可以了，坐标系原点、坐标轴朝向都无所谓的，因为模型本身已经考虑了normalization的问题。

**Comment by wwwwssssa** [comment]
**感谢**您的回答，其实我也是这样想的，只需要在同一不变的坐标系下就可以。
至于感知、规划和预测模块的坐标系的统一，可能我还需要一些步骤去处理。
**再次感谢！！！**
