### ISSUE TITLE
Multi-agent forecasting

### ISSUE THREAD

**Issue by Kenny1235** [ZikangZhou/QCNet#12]
I read your paper and I have some questions about the multi-agent forecasting. I would like to apply your model to a real life use-case and forecast trajectories for multiple agents.
Is this already possible with the code you provide? To my understanding, the decoder needs to know which target agent it should predict trajectories for. Can I just implement multiple decoder heads with shared encodings and how would I tell the decoder which agent it should predict trajectories for?

Thanks in advance!

**Comment by ZikangZhou** [comment]
The code is currently able to predict trajectories for multiple agents in a single forward pass. By default, the model predicts all agents' trajectories. But you can specify a subset of target agents by setting data['agent']['predict_mask'][non_target_indices, :] = False
