### ISSUE TITLE
Reusing of agent state/ map polygon encodings in subsequent observation windows

### ISSUE THREAD

**Issue by kennethweitzel** [ZikangZhou/QCNet#19]
The paper states: 
> Benefiting from modeling in local reference frames, the embedding of each agent state/map polygon has only one instance and can be reused in the subsequent observation windows.

As the Argoverse 2 dataset contains independent scenarios as samples, the scene features are encoded from scratch for every sample and it is not possible to reuse any embeddings.  If I want to apply your model on a real life use case where the next sample is the next observation window in time, how would I implement this reusing of the agent state/ map polygon encodings?

**Comment by Li-kewei** [comment]
I am also getting confused and hope to get a reply from the author soon.

**Comment by Li-kewei** [comment]
I am also getting confused and hope to get a reply from the author soon.

**Comment by kiwen-lee** [comment]
I am also getting confused and hope to get a reply from the author soon.

**Comment by rongxiaoqu** [comment]
I suspect that this statement is only valid when working on given dataset like argoverse, where we are given all the scene features in advance.

**Comment by kennethweitzel** [comment]
It was mentioned here: #7
It is not possible yet with this code base
