### ISSUE TITLE
conda version

### ISSUE THREAD

**Issue by zhangpaipai** [ZikangZhou/QCNet#35]
Hi, when I conduct conda env create -f environment.yml, there will be some version conflicts of conda. 
4.5.4 and 4.12.0 both have problems, but 4.10.1 can succeed.
Can I know your conda version so that I can reproduce your great work in omy own computer.

**Comment by SunHaoOne** [comment]
It's advisable to directly install the PyG, including PyTorch-GPU and the corresponding supported version of PyTorch-Lightning for PyTorch GPU.
