### ISSUE TITLE
Ask about the design of the attention layer

### ISSUE THREAD

**Issue by JYS997760473** [ZikangZhou/QCNet#42]
Hi, Dr.Zhou, I am curious about the the design of the attention layer, since these four lines look like different with the common multi-head attention:
https://github.com/ZikangZhou/QCNet/blob/55cacb418cbbce3753119c1f157360e66993d0d0/layers/attention_layer.py#L96C1-L99C40
![image](https://github.com/ZikangZhou/QCNet/assets/90627672/20afdfca-568f-4a39-9b2b-22bafb785711)
And I would like to ask why you use dot product here rather than common matrix multiplication like:
``` python
sim = torch.matmul(q_i, k_j.transpose(1,2)) * self.scale
attn = softmax(sim_test, index, ptr)
attn = self.attn_drop(attn)
return torch.matmul(attn, v_j)
```

**Comment by ares89** [comment]
It's scaled **dot-product** attention.

**Comment by rlczddl** [comment]
给后来人提示下，它这里面的attention必须用逐元素对应相乘，因为edge_index实现了对应元素的匹配，实现了一种“隔离”操作。如果用标准矩阵乘法，匹配就没意义了，直接变成全局交互了。
