### ISSUE TITLE
Visualization methods

### ISSUE THREAD

**Issue by Lionel-Lee** [ZikangZhou/QCNet#8]
Hi Zikang,

Cheers for your wonderful work! Is it possible for you guys to release the visualization code as well? As I'm not quite familiar with the argoverse dataset and its toolkit, it would be great if you could share your visualization methods. Thanks!

**Comment by ZikangZhou** [comment]
Our internal visualization tool is based on the official one in av2 API. You can find some useful utils here: https://github.com/argoverse/av2-api/blob/main/tutorials/generate_forecasting_scenario_visualizations.py, which can produce beautiful videos of traffic scenarios.
